= 创建一个Vue项目

== 使用vite创建一个vue项目
[source,bash]
....
pnpm create vite
....

.command out
[source,bash]
....
E:\workspace\font>pnpm create vite
D:/cache/pnpm/store/v3/tmp/dlx-8780      |   +1 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\cache\pnpm\store\v3
  Virtual store is at:             D:/cache/pnpm/store/v3/tmp/dlx-8780/node_modules/.pnpm
D:/cache/pnpm/store/v3/tmp/dlx-8780      | Progress: resolved 1, reused 0, downloaded 1, added 1, done
√ Project name: ... vite-hello
√ Select a framework: » Vue
√ Select a variant: » Customize with create-vue ↗
D:/cache/pnpm/store/v3/tmp/dlx-16532     |   +1 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\cache\pnpm\store\v3
  Virtual store is at:             D:/cache/pnpm/store/v3/tmp/dlx-16532/node_modules/.pnpm
D:/cache/pnpm/store/v3/tmp/dlx-16532     | Progress: resolved 1, reused 1, downloaded 0, added 1, done

Vue.js - The Progressive JavaScript Framework

√ Add TypeScript? ... No / Yes
√ Add JSX Support? ... No / Yes
√ Add Vue Router for Single Page Application development? ... No / Yes
√ Add Pinia for state management? ... No / Yes
√ Add Vitest for Unit Testing? ... No / Yes
√ Add an End-to-End Testing Solution? » Playwright
√ Add ESLint for code quality? ... No / Yes
√ Add Prettier for code formatting? ... No / Yes

Scaffolding project in E:\workspace\font\vite-hello...

Done. Now run:

  cd vite-hello
  pnpm install
  pnpm format
  pnpm dev


E:\workspace\font>
....

== 添加Tailwind CSS支持
[,bash]
....
pnpm install -D tailwindcss postcss autoprefixer
....

.生成配置文件
[,bash]
....
npx tailwindcss init -p
....

=== 修改配置文件 

.`tailwind.config.js`
[,json]
....
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
....

.`style.css`
[,css]
....
@tailwind base;
@tailwind components;
@tailwind utilities;
....

=== 问题
==== vscode 提示 Unknown at rule @tailwind
在``.vscode/settings.json``配置文件中新增：
[,json]
....
  "css.lint.unknownAtRules": "ignore"
....

== 规范与检查 Git 提交
=== Git 提交规范

* commitizen

[,bash]
....
pnpm i -D commitizen cz-customizable
....

.创建 `.cz-config.js` 
[,js]
....
module.exports = {
  //可选类型
  types: [
    { value: 'feat', name: 'feat:   新功能' },
    { value: 'fix', name: 'fix:   修复' },
    { value: 'docs', name: 'docs:   文档变更' },
    { value: 'style', name: 'style:   代码格式(不影响代码运行的变动)' },
    {
      value: 'refactor',
      name: 'refactor:重构(既不是增加feature)，也不是修复bug'
    },
    { value: 'perf', name: 'perf:   性能优化' },
    { value: 'test', name: 'test:   增加测试' },
    { value: 'chore', name: 'chore:   构建过程或辅助功能的变动' },
    { value: 'revert', name: 'revert:   回退' },
    { value: 'build', name: 'build:   打包' },
    { value: 'revert', name: 'revert:   回退' }
  ],
  //消息步骤
  messages: {
    type: '请选择提交类型',
    customScope: '请输入修改范围(可选)',
    subject: '请简要描述提交(必填)',
    body: '请输入详细描述(可选)',
    footer: '请输入要关闭的issue(可选)',
    confirmCommit: '确认以上信息提交?(y/n)'
  },
  //跳过问题
  skipQuestion: ['body', 'footer'],
  //subject文字长度默认是
  subjectLimit: 72
}
....

.`package.json`
[,json]
....
{
  "config": {
    "commitizen": {
      "path": "node_modules/cz-customizable"
    }
  }
}
....

=== 强制检查

* commitlint

[,bash]
....
pnpm install --save-dev @commitlint/config-conventional @commitlint/cli
....

.创建 `commitlint.config.js`
[,js]
....
module.exports = {
  // 继承的规则
  extends: ['@commitlint/config-conventional'],
  // 定义规则类型
  rules: {
    'body-leading-blank': [2, 'always'], // body换行
    'header-max-length': [2, 'never', 72], // header 最长72
    // type类型定义，表示git提交的 type 必须在以下类型范围内
    'type-enum': [
      2,
      'always',
      [
        'feat', // 新功能
        'fix', // 修复bug
        'docs', //文档注释
        'style', // 代码格式(不影响代码运行的变动)
        'regactor', // 重构(既不是增加feature，也不是修复bug)
        'perf', // 性能优化
        'test', // 增加测试
        'chore', // 构建过程或辅助工具的变更
        'revert', // 回退
        'build' // 打包
      ]
    ],
    // 大小写不做校验
    'subject-case': [0]
  }
}
....

* 添加husky支持

[,bash]
....
pnpm install -D husky 
....

.生成配置
[,bash]
....
npx husky install
....

* Git hooks

.检查提交信息
[,bash]
....
npx husky add .husky/commit-msg
....

. `.husky\commit-msg`
[, bash]
....
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit
....

.提交前检查
[,bash]
....
npx husky add .husky/pre-commit
....

. `.husky\pre-commit`
[,bash]
....
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
....

. `package.json`
[,json]
....
{
  ....
  "lint-staged": {
    "src/**/*.{ts,vue}": [
      "eslint --fix",
      "git add"
    ]
  }
}
....


== 添加tauri支持
[source,bash]
....
pnpm add -D @tauri-apps/cli
....

.初始化tauri
[,bash]
....
pnpm tauri init
....

.``package.json`` 添加执行脚本支持
[source,json]
....
  "scripts": {
    ......
    "tauri:dev": "tauri dev",
    "tauri:build": "tauri build"
  }
....

== 问题
=== 解决 eslint 和 prettier 冲突

[quote, 解决Eslint 和 Prettier 之间的冲突, https://juejin.cn/post/7012160233061482532]
____
冲突的本质在于 eslint既负责了代码质量检测，又负责了一部分的格式美化工作,格式化部分的部分规则和 prettier不兼容。 能不能让eslint只负责代码质量检测而让prettier负责美化呢? 好在社区有了非常好的成熟方案，即 `eslint-config-prettier` + `eslint-plugin-prettier`。

* eslint-config-prettier 的作用是关闭eslint中与prettier相互冲突的规则。
* eslint-plugin-prettier 的作用是赋予eslint用prettier格式化代码的能力。
安装依赖并修改 `.eslintrc` 文件
____

.command
[,bash]
....
pnpm i eslint-config-prettier eslint-plugin-prettier -D
....

.eslintrc.cjs
[,js]
....
{
   // 其余的配置
 - "extends": ["eslint:recommended", "standard"]
 + "extends": ["eslint:recommended", "standard",  "plugin:prettier/recommended"]
  // 其余的配置
}
....